### ISSUE TITLE
Collapse apt output in log file

### ISSUE THREAD

**Issue by jhenstridge** [canonical/has-signed-canonical-cla#10]
The majority of the log output from this action is output from apt to install python3-launchpadlib.  While this could be useful if that part of the action breaks for some reason, it usually isn't particularly interesting.

This could be improved by marking the output as collapsible with:

    core.startGroup('Installing python3-launchpadlib')
    ...
    core.endGroup()

**Comment by MarcusTomlinson** [comment]
Fixed thanks!
