### ISSUE TITLE
Allow canonical employees to contribute regardless of e-mail

### ISSUE THREAD

**Issue by stgraber** [canonical/has-signed-canonical-cla#16]
Quite a few of us have been using our `@ubuntu.com` e-mail addresses for open source contributions done as part of our work at Canonical. Currently this flags me as not having signed the CLA, which while correct is also irrelevant as I'm a Canonical employee and my copyright belongs to Canonical anyway :)

I suspect we should just change:
https://github.com/canonical/has-signed-canonical-cla/blob/main/index.js#L82

To also check for membership in the `canonical` Github organization. If someone is found to be a member, they're an employee and their copyright therefore belongs to Canonical just as it would coming from a `@canonical.com` e-mail address.

I don't believe the same thing can be done with Launchpad though as `~canonical` on Launchpad is a fully private team and so membership can't be so easily checked, but at least we can do the right thing on Github!

**Comment by SimonRichardson** [comment]
I'd even go further to say that it's trivial to sign a commit (`git commit --author=""`) with a different user/email to bypass the CLA.

https://github.com/canonical/has-signed-canonical-cla/blob/main/index.js#L66-L70

**Comment by SimonRichardson** [comment]
> then it's likely reasonable to consider them as having given their copyright to said company.

IANAL, but that seems dangerous.
