### ISSUE TITLE
Allow external contributors without LP accounts

### ISSUE THREAD

**Issue by barrettj12** [canonical/has-signed-canonical-cla#23]
We have an new external contributor who just put up [a PR](https://github.com/juju/juju/pull/14631). I asked them to sign the CLA and they did. However, this action is still failing on the PR.
- The first check is if they are a public member of the [CanonicalContributorAgreement GitHub org](https://github.com/orgs/CanonicalContributorAgreement/people). This includes a whopping 11 people, so it seems people who sign the CLA and provide their GH username are still **not added** to this group.
- The second check is: use the Git email to look up their account on Launchpad, and check if their account has signed the CLA. This person does not have an LP account, so this failed.

We should not require external contributors to create a Launchpad account. We should be grateful for their help and not force them to jump through hoops.

I don't see why we can't just directly check their GH username / commit email against the CLA data. This seems a lot simpler and more reliable.

**Comment by jhenstridge** [comment]
Note that the first check is intended to cover private members of the group (it's using a token that should be able to check those memberships). If that's not working, then perhaps the token permissions have been revoked.
