### ISSUE TITLE
Github uses different email addresses

### ISSUE THREAD

**Issue by jameinel** [canonical/has-signed-canonical-cla#31]
If you use the Github web interface to merge a commit into your branch, it commits that change with something like:
```
Author: Teodora Mihoc <38667005+tmihoc@users.noreply.github.com>
Author: Juan M. Tirado <juanmanuel-tirado@users.noreply.github.com>
```

I don't know why the former one has an opaque ID+username, and the other has only the username.

Either way, the issue is that it is now unsafe to use the Github Web to "merge this other branch" directly via the web interface.

Is there some way that we can map these users back into a launchpad account or a github account. Both of these particular people have a @canonical.com account.

Or is it simply that we need to change their Github setup somehow for how it commits on their behalf?

**Comment by lengau** [comment]
The former at least is created with the setting "Keep my email addresses private" at https://github.com/settings/emails

The configuration I have set up seems to work fine with web commits — I have my `canonical.com` email address set as my primary email address and have deselected "Keep my email addresses private."

**Comment by beliaev-maksim** [comment]
will be fixed in v2
