### ISSUE TITLE
Pass the check if user belongs to the Canonical org

### ISSUE THREAD

**Issue by sed-i** [canonical/has-signed-canonical-cla#46]
Currently the check is failing like so:
```
Checking the following user on Launchpad:
- 82407168+sed-i@users.noreply.github.com ✕ (has no Launchpad account)
```

(Which is expected to fail.)

Would it be possible to have the check pass based on membership to the Canonical org?

**Comment by beliaev-maksim** [comment]
members are not public by default 

reject, will be done by allowing users to sign their github account which will unlock anonymous emails

**Comment by sed-i** [comment]
How do I do that @beliaev-maksim ?

**Comment by beliaev-maksim** [comment]
new CLA service: https://ubuntu.com/legal/contributors

but first need to merge #66
and then update to the new endpoints
