### ISSUE TITLE
Node 16 is deprecated

### ISSUE THREAD

**Issue by barrettj12** [canonical/has-signed-canonical-cla#49]
This action is using Node 16 which is deprecated. When it is run, GitHub prints a warning:
```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: canonical/has-signed-canonical-cla@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

We should update it to use Node 20 and release a v2.

**Comment by dimaqq** [comment]
I see that you've moved this action to node 16 back in the day, Jordan. Would you do the honours and make a PR to update to 20?
