### ISSUE TITLE
action continues running on apt errors

### ISSUE THREAD

**Issue by jhenstridge** [canonical/has-signed-canonical-cla#8]
The way the action invokes `exec.exec()` does not stop execution of the action:

https://github.com/canonical/has-signed-canonical-cla/blob/c4e25ca57be6bc0bd08ef5eae1a068c0d486ead1/index.js#L10-L17

If exec() call throws an async exception, the `catch()` callback will mark the action as failed but allow execution to continue.

As an alternative, I would suggest adding a catch() callback to the `run()` call at the very end of the file, and let exceptions bubble up to that top level.

**Comment by MarcusTomlinson** [comment]
Fixed thanks!
